'''Exemplo de operações de str'''
frase = str(input('Escreva uma frase com a palavra vida: ')) .strip() #.lstrip ou .rstrp
print(f'O número de caractéres é: {len(frase)}')
print(f'O terceiro carctér: {frase[3]}')
print(f'O intervalo de caracteres entre zero e seis: {frase[0:6]}')
print(f'O inverlado de caracteres entre zero e treze com altenância de escolha de dois: {frase[0:13:2]}')
print(f'A frase do início até seu décimo caractér: {frase[:10]}')
print(f'O décimo caractér até o seu último: {frase[10:]}')
print(f'As letras -a- que existem na frase: {frase.count("a")}')
print(f'A letra l no intervalo de caracteres de zero a cinco: {frase.count("l", 0, 5)}')
print(f'A letra: é, dentro do texto: {frase.find("é")}')
print(f'Substituição da palavra vida pela palavra bola: {frase.replace("vida", "bola")}')
print(f'A frase inteiramente maiúscula: {frase.upper()}')
print(f'A frase inteiramente minúscula: {frase.lower()}')
print(f'A primeira letra da primeira palavra maiúscula: {frase.capitalize()}')
print(f'A inicial de cada palavra em maiúscula: {frase.title()}')
print(f'A frase dividida: {frase.split()}')
print(f'A frase junta: {"-".join(frase)}')
print(f'Verifique se a palavra vida está na frase: {"vida" in frase}')
