n = str(input('Digite aqui: '))
print(f'Qual é a sua classe primitiva? {type(n)}')
print(f'O termo é composto só por espaços? {n.isspace()}')
print(f'O termo é composto só de letras? {n.isalpha()}')
print(f'O termo é composto só por números? {n.isnumeric()}')
print(f'O termo é composto por letras e números? {n.isalnum()}')
print(f'O termo é composto só por letras mínúsculas? {n.islower()}')
print(f'O termo é composto só por letras maiúsculas? {n.isupper()}')
print(f'O termo está capitalizado? {n.istitle()}')
