n1 = int(input('Um valor: '))
n2 = int(input('Outro valor: '))
print(f'A soma vale: {n1+n2}.', end=' ')
print(f'A subtração vale: {n1-n2}.')
print(f'E a multiplicação e divisão valem respectivamente: \n{n1*n2} \n{n1/n2:.2f}')
